# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='wecontent',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
